# build environment
FROM node:16 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY yarn.lock .
RUN yarn install
RUN yarn add react-scripts@3.4.1 -g --silent

# build the react app
RUN yarn build

# add app
COPY . ./

# expose the port
EXPOSE 3000

# start the server
CMD ["yarn", "run", "start-server"]